version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: panda
      MONGO_INITDB_ROOT_PASSWORD: panda
    networks:
      - mongo_network
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: panda
      ME_CONFIG_MONGODB_ADMINPASSWORD: panda
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - mongo_network
    ports:
      - "8081:8081"

networks:
  mongo_network:
    driver: bridge


  
